### ISSUE TITLE
"Om"-knappen fungerer ikke (i TEST og QA)

### ISSUE THREAD

**Issue by areedv** [Rapporteket/intensiv#4]
Det kommer ingen info opp når man trykker på "Om" lenken oppe i høyre hjørne av appen:
![image](https://user-images.githubusercontent.com/1522857/221117666-2c54554b-68d7-4830-b140-758805bb1172.png)
Det er derfor ikke så lett å se hvilke versjon som kjører, bla.

**Comment by lenaringstado** [comment]
Bug er rettet
